import DOMPurify from 'dompurify'
import katex from 'katex'

/**
 * Rich-text model: question content is stored as sanitized HTML strings (no
 * schema migration — legacy plain-text values are valid HTML). Math is authored
 * inline as LaTeX between $…$ (inline) or $$…$$ (display) and rendered with KaTeX
 * at display time, so it works in the editor output, on screen, and in PDF.
 */

const ALLOWED_TAGS = [
  'p', 'br', 'strong', 'b', 'em', 'i', 'u', 's', 'sub', 'sup',
  'ul', 'ol', 'li', 'blockquote', 'code', 'pre', 'span',
]
const ALLOWED_ATTR = ['class']

/** Sanitize author HTML down to a safe formatting subset. */
export function sanitizeRichHtml(html: string | null | undefined): string {
  if (!html) return ''
  return DOMPurify.sanitize(html, { ALLOWED_TAGS, ALLOWED_ATTR })
}

/** Fast tag strip for search/matching (cheap, runs per-question per-keystroke). */
export function stripHtml(html: string | null | undefined): string {
  if (!html) return ''
  return html
    .replace(/<[^>]*>/g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/\s+/g, ' ')
    .trim()
}

/** Accurate plain-text extraction (DOM-based) for excerpts / DOCX fallback. */
export function richTextToPlain(html: string | null | undefined): string {
  if (!html) return ''
  if (typeof DOMParser === 'undefined') return stripHtml(html)
  const doc = new DOMParser().parseFromString(html, 'text/html')
  return (doc.body.textContent ?? '').replace(/\s+/g, ' ').trim()
}

/** True when the value has no visible text (covers empty `<p></p>` from TipTap). */
export function isRichTextEmpty(value: string | null | undefined): boolean {
  if (!value) return true
  return stripHtml(value).length === 0
}

/** Editor value → stored value: '' when effectively empty, else sanitized HTML. */
export function normalizeRichValue(html: string | null | undefined): string {
  if (isRichTextEmpty(html)) return ''
  return sanitizeRichHtml(html)
}

const MATH_RE = /\$\$([\s\S]+?)\$\$|\$([^$\n]+?)\$/g

/**
 * Walk an element's text nodes and replace $…$ / $$…$$ segments with KaTeX.
 * KaTeX output is generated by us (trusted), rendered directly into the DOM, so
 * the surrounding author HTML can stay sanitized to a minimal tag set.
 */
export function renderMathInElement(root: HTMLElement): void {
  if (!root.textContent || !root.textContent.includes('$')) return

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement
      if (!parent || parent.closest('code, pre, .katex')) {
        return NodeFilter.FILTER_REJECT
      }
      return node.textContent && node.textContent.includes('$')
        ? NodeFilter.FILTER_ACCEPT
        : NodeFilter.FILTER_REJECT
    },
  })

  const targets: Text[] = []
  let node = walker.nextNode()
  while (node) {
    targets.push(node as Text)
    node = walker.nextNode()
  }

  for (const textNode of targets) replaceMathInTextNode(textNode)
}

function replaceMathInTextNode(textNode: Text): void {
  const text = textNode.textContent ?? ''
  MATH_RE.lastIndex = 0
  if (!MATH_RE.test(text)) return
  MATH_RE.lastIndex = 0

  const frag = document.createDocumentFragment()
  let lastIndex = 0
  let match: RegExpExecArray | null

  while ((match = MATH_RE.exec(text)) !== null) {
    const [full, displayLatex, inlineLatex] = match
    if (match.index > lastIndex) {
      frag.appendChild(document.createTextNode(text.slice(lastIndex, match.index)))
    }
    const latex = displayLatex ?? inlineLatex ?? ''
    const span = document.createElement('span')
    try {
      katex.render(latex, span, {
        displayMode: Boolean(displayLatex),
        throwOnError: false,
      })
    } catch {
      span.textContent = full
    }
    frag.appendChild(span)
    lastIndex = match.index + full.length
  }

  if (lastIndex < text.length) {
    frag.appendChild(document.createTextNode(text.slice(lastIndex)))
  }
  textNode.parentNode?.replaceChild(frag, textNode)
}
